// Shark.swift
// Generated by Shark https://github.com/kaandedeoglu/Shark

import SwiftUI

// swiftlint:disable all
// swiftformat:disable all
private let bundle: Bundle = {
    class Custom {}
    return Bundle(for: Custom.self)
}()

extension String {
    public var localizedStringKey: LocalizedStringKey { .init(self) }
}

public enum R {
    public enum I: CaseIterable {
    }

    public enum C: CaseIterable {
    }

    public enum L {
        /// Idle
        public static var Activity_IDLE: String { return NSLocalizedString("Activity_IDLE", bundle: bundle, comment: "") }

        /// Playing
        public static var Activity_PLAYING: String { return NSLocalizedString("Activity_PLAYING", bundle: bundle, comment: "") }

        /// Playing and recording
        public static var Activity_PLAYING_RECORDING: String { return NSLocalizedString("Activity_PLAYING_RECORDING", bundle: bundle, comment: "") }

        /// Recording
        public static var Activity_RECORDING: String { return NSLocalizedString("Activity_RECORDING", bundle: bundle, comment: "") }

        /// LSAudio
        public static var App_NAME: String { return NSLocalizedString("App_NAME", bundle: bundle, comment: "") }

        /// Audio Processes
        public static var App_PROCESSES_WINDOW: String { return NSLocalizedString("App_PROCESSES_WINDOW", bundle: bundle, comment: "") }

        /// Cancel
        public static var Common_CANCEL: String { return NSLocalizedString("Common_CANCEL", bundle: bundle, comment: "") }

        /// Clear
        public static var Common_CLEAR: String { return NSLocalizedString("Common_CLEAR", bundle: bundle, comment: "") }

        /// Copy
        public static var Common_COPY: String { return NSLocalizedString("Common_COPY", bundle: bundle, comment: "") }

        /// Done
        public static var Common_DONE: String { return NSLocalizedString("Common_DONE", bundle: bundle, comment: "") }

        /// Export
        public static var Common_EXPORT: String { return NSLocalizedString("Common_EXPORT", bundle: bundle, comment: "") }

        /// Show All Processes…
        public static var Common_OPEN_WINDOW: String { return NSLocalizedString("Common_OPEN_WINDOW", bundle: bundle, comment: "") }

        /// Quit
        public static var Common_QUIT: String { return NSLocalizedString("Common_QUIT", bundle: bundle, comment: "") }

        /// Refresh
        public static var Common_REFRESH: String { return NSLocalizedString("Common_REFRESH", bundle: bundle, comment: "") }

        /// Settings
        public static var Common_SETTINGS: String { return NSLocalizedString("Common_SETTINGS", bundle: bundle, comment: "") }

        /// Show idle clients
        public static var Common_SHOW_IDLE: String { return NSLocalizedString("Common_SHOW_IDLE", bundle: bundle, comment: "") }

        /// Show executable paths
        public static var Common_SHOW_PATHS: String { return NSLocalizedString("Common_SHOW_PATHS", bundle: bundle, comment: "") }

        /// %d active
        public static func Count_ACTIVE(_ value1: Int) -> String {
            return String(format: NSLocalizedString("Count_ACTIVE", bundle: bundle, comment: ""), value1)
        }

        /// %d playing
        public static func Count_PLAYING(_ value1: Int) -> String {
            return String(format: NSLocalizedString("Count_PLAYING", bundle: bundle, comment: ""), value1)
        }

        /// %d recording
        public static func Count_RECORDING(_ value1: Int) -> String {
            return String(format: NSLocalizedString("Count_RECORDING", bundle: bundle, comment: ""), value1)
        }

        /// %d registered
        public static func Count_REGISTERED(_ value1: Int) -> String {
            return String(format: NSLocalizedString("Count_REGISTERED", bundle: bundle, comment: ""), value1)
        }

        /// OK
        public static var Error_DISMISS: String { return NSLocalizedString("Error_DISMISS", bundle: bundle, comment: "") }

        /// LSAudio Error
        public static var Error_TITLE: String { return NSLocalizedString("Error_TITLE", bundle: bundle, comment: "") }

        /// Changed
        public static var Event_CHANGE: String { return NSLocalizedString("Event_CHANGE", bundle: bundle, comment: "") }

        /// Present
        public static var Event_PRESENT: String { return NSLocalizedString("Event_PRESENT", bundle: bundle, comment: "") }

        /// Started
        public static var Event_START: String { return NSLocalizedString("Event_START", bundle: bundle, comment: "") }

        /// Stopped
        public static var Event_STOP: String { return NSLocalizedString("Event_STOP", bundle: bundle, comment: "") }

        /// Copy Event Log
        public static var Export_COPY_EVENTS: String { return NSLocalizedString("Export_COPY_EVENTS", bundle: bundle, comment: "") }

        /// Copy JSON
        public static var Export_COPY_JSON: String { return NSLocalizedString("Export_COPY_JSON", bundle: bundle, comment: "") }

        /// Copy Plain Text
        public static var Export_COPY_PLAIN: String { return NSLocalizedString("Export_COPY_PLAIN", bundle: bundle, comment: "") }

        /// Export Event Log…
        public static var Export_EVENTS: String { return NSLocalizedString("Export_EVENTS", bundle: bundle, comment: "") }

        /// Export JSON…
        public static var Export_JSON: String { return NSLocalizedString("Export_JSON", bundle: bundle, comment: "") }

        /// Export Plain Text…
        public static var Export_PLAIN: String { return NSLocalizedString("Export_PLAIN", bundle: bundle, comment: "") }

        /// Activity
        public static var Inspector_ACTIVITY: String { return NSLocalizedString("Inspector_ACTIVITY", bundle: bundle, comment: "") }

        /// Audio Devices
        public static var Inspector_AUDIO_DEVICES: String { return NSLocalizedString("Inspector_AUDIO_DEVICES", bundle: bundle, comment: "") }

        /// Bundle ID
        public static var Inspector_BUNDLE_ID: String { return NSLocalizedString("Inspector_BUNDLE_ID", bundle: bundle, comment: "") }

        /// Executable
        public static var Inspector_EXECUTABLE: String { return NSLocalizedString("Inspector_EXECUTABLE", bundle: bundle, comment: "") }

        /// Identity
        public static var Inspector_IDENTITY: String { return NSLocalizedString("Inspector_IDENTITY", bundle: bundle, comment: "") }

        /// No device reported
        public static var Inspector_NO_DEVICES: String { return NSLocalizedString("Inspector_NO_DEVICES", bundle: bundle, comment: "") }

        /// %@ playing, %@ recording
        public static func MenuBar_COUNT_ACCESSIBILITY(_ value1: String,_ value2: String) -> String {
            return String(format: NSLocalizedString("MenuBar_COUNT_ACCESSIBILITY", bundle: bundle, comment: ""), value1, value2)
        }

        /// Playing
        public static var Scope_PLAYING: String { return NSLocalizedString("Scope_PLAYING", bundle: bundle, comment: "") }

        /// Recording
        public static var Scope_RECORDING: String { return NSLocalizedString("Scope_RECORDING", bundle: bundle, comment: "") }

        /// Filter by process name, bundle ID, PID, device, or path
        public static var Search_PROMPT: String { return NSLocalizedString("Search_PROMPT", bundle: bundle, comment: "") }

        /// Confirm before SIGTERM
        public static var Settings_CONFIRM_QUICK_TERMINATION: String { return NSLocalizedString("Settings_CONFIRM_QUICK_TERMINATION", bundle: bundle, comment: "") }

        /// Applies to the quick terminate button in the menu bar panel.
        public static var Settings_CONFIRM_QUICK_TERMINATION_NOTE: String { return NSLocalizedString("Settings_CONFIRM_QUICK_TERMINATION_NOTE", bundle: bundle, comment: "") }

        /// (C) Dr. Michael 'Mickey' Lauer – made with love in Neu-Isenburg – [https://www.vanille.de](https://www.vanille.de)
        public static var Settings_CREDITS: String { return NSLocalizedString("Settings_CREDITS", bundle: bundle, comment: "") }

        /// General
        public static var Settings_GENERAL: String { return NSLocalizedString("Settings_GENERAL", bundle: bundle, comment: "") }

        /// Idle clients are registered with coreaudiod but are not currently using audio.
        public static var Settings_IDLE_NOTE: String { return NSLocalizedString("Settings_IDLE_NOTE", bundle: bundle, comment: "") }

        /// Activity
        public static var Settings_SORT_ACTIVITY: String { return NSLocalizedString("Settings_SORT_ACTIVITY", bundle: bundle, comment: "") }

        /// Alphabetically
        public static var Settings_SORT_ALPHABETICAL: String { return NSLocalizedString("Settings_SORT_ALPHABETICAL", bundle: bundle, comment: "") }

        /// Sort by
        public static var Settings_SORT_BY: String { return NSLocalizedString("Settings_SORT_BY", bundle: bundle, comment: "") }

        /// Audio device
        public static var Settings_SORT_DEVICE: String { return NSLocalizedString("Settings_SORT_DEVICE", bundle: bundle, comment: "") }

        /// Process ID
        public static var Settings_SORT_PID: String { return NSLocalizedString("Settings_SORT_PID", bundle: bundle, comment: "") }

        /// Event History
        public static var Sidebar_EVENTS: String { return NSLocalizedString("Sidebar_EVENTS", bundle: bundle, comment: "") }

        /// Processes
        public static var Sidebar_PROCESSES: String { return NSLocalizedString("Sidebar_PROCESSES", bundle: bundle, comment: "") }

        /// Send Signal…
        public static var Signal_ACTION: String { return NSLocalizedString("Signal_ACTION", bundle: bundle, comment: "") }

        /// Authorize administrator access if required
        public static var Signal_AUTHORIZE: String { return NSLocalizedString("Signal_AUTHORIZE", bundle: bundle, comment: "") }

        /// Send SIGTERM
        public static var Signal_CONFIRM_ACTION: String { return NSLocalizedString("Signal_CONFIRM_ACTION", bundle: bundle, comment: "") }

        /// This asks %@ (PID %d) to terminate.
        public static func Signal_CONFIRM_MESSAGE(_ value1: String,_ value2: Int) -> String {
            return String(format: NSLocalizedString("Signal_CONFIRM_MESSAGE", bundle: bundle, comment: ""), value1, value2)
        }

        /// Send SIGTERM?
        public static var Signal_CONFIRM_TITLE: String { return NSLocalizedString("Signal_CONFIRM_TITLE", bundle: bundle, comment: "") }

        /// Dry run: %@ would be sent to %d processes.
        public static func Signal_DRY_RESULT(_ value1: String,_ value2: Int) -> String {
            return String(format: NSLocalizedString("Signal_DRY_RESULT", bundle: bundle, comment: ""), value1, value2)
        }

        /// Dry run
        public static var Signal_DRY_RUN: String { return NSLocalizedString("Signal_DRY_RUN", bundle: bundle, comment: "") }

        /// Could not signal: %@
        public static func Signal_FAILED(_ value1: String) -> String {
            return String(format: NSLocalizedString("Signal_FAILED", bundle: bundle, comment: ""), value1)
        }

        /// Include idle clients
        public static var Signal_INCLUDE_IDLE: String { return NSLocalizedString("Signal_INCLUDE_IDLE", bundle: bundle, comment: "") }

        /// %d matching processes
        public static func Signal_MATCHES(_ value1: Int) -> String {
            return String(format: NSLocalizedString("Signal_MATCHES", bundle: bundle, comment: ""), value1)
        }

        /// 1 matching process
        public static var Signal_MATCH_ONE: String { return NSLocalizedString("Signal_MATCH_ONE", bundle: bundle, comment: "") }

        /// No matching process
        public static var Signal_NO_MATCH: String { return NSLocalizedString("Signal_NO_MATCH", bundle: bundle, comment: "") }

        /// Administrator authorization is required for: %@
        public static func Signal_PERMISSION_DENIED(_ value1: String) -> String {
            return String(format: NSLocalizedString("Signal_PERMISSION_DENIED", bundle: bundle, comment: ""), value1)
        }

        /// Preview
        public static var Signal_PREVIEW: String { return NSLocalizedString("Signal_PREVIEW", bundle: bundle, comment: "") }

        /// Terminate %@ (SIGTERM)
        public static func Signal_QUICK_TERMINATE(_ value1: String) -> String {
            return String(format: NSLocalizedString("Signal_QUICK_TERMINATE", bundle: bundle, comment: ""), value1)
        }

        /// Enter a target before including every registered audio client.
        public static var Signal_REFUSE_ALL_IDLE: String { return NSLocalizedString("Signal_REFUSE_ALL_IDLE", bundle: bundle, comment: "") }

        /// Send %@
        public static func Signal_SEND(_ value1: String) -> String {
            return String(format: NSLocalizedString("Signal_SEND", bundle: bundle, comment: ""), value1)
        }

        /// Sent %@ to %d processes.
        public static func Signal_SENT(_ value1: String,_ value2: Int) -> String {
            return String(format: NSLocalizedString("Signal_SENT", bundle: bundle, comment: ""), value1, value2)
        }

        /// Sent %@ to 1 process.
        public static func Signal_SENT_ONE(_ value1: String) -> String {
            return String(format: NSLocalizedString("Signal_SENT_ONE", bundle: bundle, comment: ""), value1)
        }

        /// Signal
        public static var Signal_SIGNAL: String { return NSLocalizedString("Signal_SIGNAL", bundle: bundle, comment: "") }

        /// Stop All Active Audio…
        public static var Signal_STOP_ALL: String { return NSLocalizedString("Signal_STOP_ALL", bundle: bundle, comment: "") }

        /// Target
        public static var Signal_TARGET: String { return NSLocalizedString("Signal_TARGET", bundle: bundle, comment: "") }

        /// PID, bundle ID, or name; empty means all active
        public static var Signal_TARGET_PLACEHOLDER: String { return NSLocalizedString("Signal_TARGET_PLACEHOLDER", bundle: bundle, comment: "") }

        /// Signal Audio Processes
        public static var Signal_TITLE: String { return NSLocalizedString("Signal_TITLE", bundle: bundle, comment: "") }

        /// Updated %@
        public static func Status_LAST_UPDATED(_ value1: String) -> String {
            return String(format: NSLocalizedString("Status_LAST_UPDATED", bundle: bundle, comment: ""), value1)
        }

        /// Reading CoreAudio…
        public static var Status_LOADING: String { return NSLocalizedString("Status_LOADING", bundle: bundle, comment: "") }

        /// CoreAudio notifications and periodic verification keep this list current.
        public static var Status_MONITOR_NOTE: String { return NSLocalizedString("Status_MONITOR_NOTE", bundle: bundle, comment: "") }

        /// No process is currently playing or recording audio.
        public static var Status_NO_ACTIVE: String { return NSLocalizedString("Status_NO_ACTIVE", bundle: bundle, comment: "") }

        /// No process is currently recording audio.
        public static var Status_NO_INPUT: String { return NSLocalizedString("Status_NO_INPUT", bundle: bundle, comment: "") }

        /// No process is currently playing audio.
        public static var Status_NO_OUTPUT: String { return NSLocalizedString("Status_NO_OUTPUT", bundle: bundle, comment: "") }

        /// No audio process matches the current filter.
        public static var Status_NO_RESULTS: String { return NSLocalizedString("Status_NO_RESULTS", bundle: bundle, comment: "") }

        /// Bundle ID
        public static var Table_BUNDLE_ID: String { return NSLocalizedString("Table_BUNDLE_ID", bundle: bundle, comment: "") }

        /// Devices
        public static var Table_DEVICES: String { return NSLocalizedString("Table_DEVICES", bundle: bundle, comment: "") }

        /// Event
        public static var Table_EVENT: String { return NSLocalizedString("Table_EVENT", bundle: bundle, comment: "") }

        /// Input
        public static var Table_INPUT: String { return NSLocalizedString("Table_INPUT", bundle: bundle, comment: "") }

        /// Output
        public static var Table_OUTPUT: String { return NSLocalizedString("Table_OUTPUT", bundle: bundle, comment: "") }

        /// Executable Path
        public static var Table_PATH: String { return NSLocalizedString("Table_PATH", bundle: bundle, comment: "") }

        /// PID
        public static var Table_PID: String { return NSLocalizedString("Table_PID", bundle: bundle, comment: "") }

        /// Process
        public static var Table_PROCESS: String { return NSLocalizedString("Table_PROCESS", bundle: bundle, comment: "") }

        /// Time
        public static var Table_TIME: String { return NSLocalizedString("Table_TIME", bundle: bundle, comment: "") }
    }

    public enum D: CaseIterable {
    }
}
